# Generated by Django 5.0.7 on 2024-07-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_userplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('enable', models.BooleanField(default=True)),
                ('shape', models.IntegerField(choices=[(1, 'circle'), (2, 'square'), (3, 'etc')])),
                ('title_position', models.IntegerField(choices=[(1, 'hidden'), (2, 'outside')])),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('align', models.IntegerField(choices=[(1, 'center'), (2, 'left'), (3, 'right')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.user')),
            ],
        ),
    ]
