# Generated by Django 5.0.7 on 2024-07-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_widget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='plan',
            new_name='Plan',
        ),
    ]
