# Generated by Django 5.0.7 on 2024-07-18 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewer_session', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('os', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
            ],
        ),
    ]
