# Generated by Django 5.0.7 on 2024-07-18 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='viewer_session',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
