# Generated by Django 5.0.7 on 2024-07-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_alter_discountcode_id_alter_viewer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.discountcode'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
