# Generated by Django 5.0.7 on 2024-07-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_alter_payment_discount_code_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.IntegerField(),
        ),
    ]
