# Generated by Django 5.0.7 on 2024-07-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_alter_discountcode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='align',
            field=models.CharField(choices=[('center', 'CENTER'), ('left', 'LEFT'), ('right', 'RIGHT')], max_length=6),
        ),
        migrations.AlterField(
            model_name='widget',
            name='shape',
            field=models.CharField(choices=[('circle', 'CIRCLE'), ('square', 'SQUARE'), ('etc', 'ETC')], max_length=6),
        ),
        migrations.AlterField(
            model_name='widget',
            name='title_position',
            field=models.CharField(choices=[('hidden', 'HIDDEN'), ('outside', 'outside')], max_length=7),
        ),
    ]
